## Numpy

In [1]:
import numpy as np

1. Create an `ndarray` of shape (3,5). All values of the array are 100.

In [2]:
arr = np.full((3, 5), 100)
print(arr)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


2. Create a border of zeros that surround the result in Question 1, so that the output is of shape (5,7), the outside values are 0 and the inside values are 100. 

In [3]:
board = np.zeros((5, 7))
board[1:1+arr.shape[0], 1:1+arr.shape[1]] = arr
print(board)

[[  0.   0.   0.   0.   0.   0.   0.]
 [  0. 100. 100. 100. 100. 100.   0.]
 [  0. 100. 100. 100. 100. 100.   0.]
 [  0. 100. 100. 100. 100. 100.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]]


3. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.


In [4]:
diag = np.zeros((5,5))
for i in range(diag.shape[0] - 1):
    diag[i + 1, i] = i + 1
print(diag)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


4. Create a checkerboard 8x8 matrix using the tile function

In [5]:
strip = np.array([[0,1],[1,0]])
checkboard = np.tile(strip, (4, 4))
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


5. Sort a 2d-array by the nth column

In [6]:
rand_arr = np.random.rand(10, 10)
nth_col = 6
sort_arr = rand_arr[np.argsort(rand_arr[:, nth_col])]
print(sort_arr)

[[9.65549767e-01 2.04498831e-01 3.70093136e-01 1.90465893e-02
  2.16913764e-01 6.92557519e-01 1.67459013e-01 5.42564627e-01
  3.27291655e-01 6.17149786e-02]
 [5.93771653e-01 2.73850972e-01 6.44743360e-01 8.96352131e-01
  4.38344791e-01 7.16929626e-01 1.82559765e-01 6.86183296e-01
  8.78443368e-01 8.31907892e-01]
 [9.51060605e-01 9.62605682e-01 1.23616451e-01 4.44477589e-01
  3.64507073e-01 1.21910714e-01 2.17081169e-01 5.69690486e-02
  8.59118748e-01 7.05897441e-02]
 [3.55591685e-01 2.96719293e-01 1.04372903e-02 1.64189985e-01
  7.01787170e-01 6.26736408e-01 5.49174044e-01 9.75603090e-01
  3.69265408e-01 8.91075347e-01]
 [3.93449411e-01 9.16780792e-01 1.07905974e-01 1.32516591e-01
  5.55983445e-02 9.02550432e-01 5.81413999e-01 2.72160777e-01
  9.20724692e-01 7.11880075e-01]
 [3.96571936e-04 8.14783955e-01 1.45429952e-01 3.09030264e-01
  4.08336758e-01 5.60252396e-01 7.48318799e-01 5.06300967e-01
  3.90815223e-01 3.42442490e-01]
 [8.92752203e-01 5.12362296e-01 5.11287921e-01 7.05973010e

6. Compute a matrix rank

In [7]:
np.linalg.matrix_rank(np.eye(4))

4

7. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [8]:
n1 = np.random.randint(10, size=(5, 5, 3))
n2 = np.random.randint(10, size=(5, 5))
product = n1 * n2[:,:,np.newaxis]

8. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [9]:
rand_2 = np.random.randint(10, size=(16, 16))
sum_arr2 = rand_2.reshape(4,4,4,4).sum(axis=(1,3))

9. Get the n largest values of an array

In [11]:
rand_3 =  np.random.rand(10, 10)
print(rand_3)
np.max(rand_3)

[[0.39238683 0.16580627 0.37560263 0.49361291 0.15612707 0.08741449
  0.71655609 0.77495269 0.46872513 0.01520342]
 [0.29603495 0.53917269 0.68834457 0.75650094 0.84168882 0.51537311
  0.93572369 0.67193056 0.39764428 0.11204518]
 [0.5054558  0.21437057 0.22893857 0.0895668  0.38859574 0.69387191
  0.15156283 0.65827634 0.08339113 0.87802149]
 [0.92830144 0.75321234 0.95074573 0.44906887 0.50410035 0.30238758
  0.17929575 0.27446624 0.93348508 0.26438285]
 [0.38241341 0.89743289 0.04182949 0.94025593 0.67554861 0.02898007
  0.7506179  0.64870352 0.70280496 0.98584924]
 [0.56869569 0.10205461 0.33343004 0.35474567 0.18002474 0.18784772
  0.40109287 0.80560689 0.94289362 0.12827742]
 [0.36329482 0.00247012 0.32014274 0.95918089 0.22906159 0.26080218
  0.64157712 0.33345961 0.98618508 0.62235365]
 [0.64889597 0.98110263 0.41366767 0.70305732 0.41301418 0.48845399
  0.36862041 0.78624287 0.21522228 0.28318377]
 [0.19643813 0.51067225 0.19877232 0.65962003 0.17594069 0.93543313
  0.74307698

0.9861850768813856

10. Implement the Game of Life using numpy arrays

In [55]:
# reference from https://www.jpytr.com/post/game_of_life/
def play_game(size=(50, 50), initial_prob_life=0.5, animation_kwargs=None, marker_size=300):
    """
    Implementation of Conway's Game of Life
    """
    board = get_board(size)
    status = get_init_status(size, initial_prob_life)
    
    fig, axes = plt.subplots(figsize=(15, 15))
    scatter = axes.scatter(*board, animated=True, s=marker_size, edgecolor=None)
    axes.text(0.5, 0.965, "CONWAY'S ", transform=axes.transAxes, ha="right", va="bottom", color="w", fontsize=25,
              family="sans-serif", fontweight="light")
    axes.text(0.5, 0.965, "GAME OF LIFE", transform=axes.transAxes, ha="left", va="bottom", color="dodgerblue",
              fontsize=25, family="sans-serif", fontweight="bold")
    axes.set_facecolor("black")
    axes.get_xaxis().set_visible(False)
    axes.get_yaxis().set_visible(False)
        
    def update(frame):
        nonlocal status
        status, live_neigbors = apply_conways_game_of_life_rules(status)
        colors = get_updated_colors(status, live_neigbors)
        scatter.set_facecolor(colors)
        return scatter
    
    animation_kwargs = {} if animation_kwargs is None else animation_kwargs
    return FuncAnimation(fig, update, **animation_kwargs)

def get_board(size):
    xs = np.arange(0, size[0])
    ys = np.arange(0, size[1])
    board = np.meshgrid(xs, ys)
    return board

def get_init_status(size, initial_prob_life):
    status = np.random.uniform(0, 1, size=size) <= initial_prob_life
    return status

def apply_conways_game_of_life_rules(status):
    """Applies Conway's Game of Life rules given the current status of the game
    
    Rules:
        1. Any live cell with fewer than two live neighbors dies, as if by underpopulation.
        2. Any live cell with two or three live neighbors lives on to the next generation.
        3. Any live cell with more than three live neighbors dies, as if by overpopulation.
        4. Any dead cell with exactly three live neighbors becomes a live cell, as if by reproduction.
        
    Returns
    -------
    new_status, new_neighbors: tuple
        A tuple containing an array representing the new status of each square on the board, and a second array
        representing the number of neighbors post update
    
    """
    live_neighbors = count_live_neighbors(status)
    survive_underpopulation = live_neighbors >= 2
    survive_overpopulation = live_neighbors <= 3
    survive = status * survive_underpopulation * survive_overpopulation
    new_status = np.where(live_neighbors==3, True, survive)  # Reproduce
    new_neighbors = count_live_neighbors(new_status)
    return new_status, new_neighbors 

def count_live_neighbors(status):
    """Counts the number of neighboring live cells"""
    kernel = np.array(
        [[1, 1, 1],
         [1, 0, 1],
         [1, 1, 1]]
    )
    c = convolve2d(status, kernel, mode='same', boundary="wrap")
    return c

def get_updated_colors(status, c):
    cmap = mpl.cm.Blues_r
    rescale = c / 8  # Maximum of 8 neighbors
    colors = [cmap(neighbors) for neighbors in rescale.flatten()]
    is_live = status.flatten()
    colors = [(r, g, b, 0.9) if live else (r, g, b, 0) for live, (r, g, b, a) in zip(is_live, colors)]
    return colors

for i in range(5):
    ani = play_game(
        size=(100, 100),
        marker_size=100,
        initial_prob_life=0.5,
        animation_kwargs={
            "frames": 300,
        }
    )

    ani.save(f'game_of_life_{i}.mp4',
             writer=animation.FFMpegFileWriter())

Check https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb for more Numpy exercises.

## Pandas

In [12]:
import pandas as pd
import seaborn as sb

1. Using NumPy, create a Pandas DataFrame with five rows and three columns

In [13]:
d = pd.DataFrame(index=np.arange(5), columns=np.arange(3))
print(d)

     0    1    2
0  NaN  NaN  NaN
1  NaN  NaN  NaN
2  NaN  NaN  NaN
3  NaN  NaN  NaN
4  NaN  NaN  NaN


The following six questions depend on the penguins dataset.

In [14]:
df_penguins = sb.load_dataset('penguins')

2. What function can we use to drop the rows that have missing data?

In [15]:
df_full = df_penguins.dropna()

3. By default, will the function in Question 2 modify df_penguins or will it return a copy?

It returns a copy.

4. Let df_full be the dataframe obtained from dropping rows with missing data. What is the average bill length of a penguin, in millimeters, in this (df_full) data set?

In [16]:
df_full["bill_length_mm"].mean()

43.99279279279279

5. Which species has the longest flippers?

In [17]:
df_full.groupby("species").mean()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
species                                                                 
Adelie          38.823973      18.347260         190.102740  3706.164384
Chinstrap       48.833824      18.420588         195.823529  3733.088235
Gentoo          47.568067      14.996639         217.235294  5092.436975

Gentoo

6. Which two species have the most similar mean weight?

   Adelie & Chinstrap

7. How could you sort by species first, then by body mass?

In [18]:
df_full.sort_values(by = ["species", "body_mass_g"], ascending = [True, True])

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
58   Adelie     Biscoe            36.5           16.6              181.0   
64   Adelie     Biscoe            36.4           17.1              184.0   
54   Adelie     Biscoe            34.5           18.1              187.0   
98   Adelie      Dream            33.1           16.1              178.0   
116  Adelie  Torgersen            38.6           17.0              188.0   
..      ...        ...             ...            ...                ...   
331  Gentoo     Biscoe            49.8           15.9              229.0   
297  Gentoo     Biscoe            51.1           16.3              220.0   
337  Gentoo     Biscoe            48.8           16.2              222.0   
253  Gentoo     Biscoe            59.6           17.0              230.0   
237  Gentoo     Biscoe            49.2           15.2              221.0   

     body_mass_g     sex  
58        2850.0  Female  
64        2850.0  Female  
54        2900.0  Female  
98        2900.0  Female  
116       2900.0  Female  
..           ...     ...  
331       5950.0    Male  
297       6000.0    Male  
337       6000.0    Male  
253       6050.0    Male  
237       6300.0    Male  

[333 rows x 7 columns]

The following three questions depend on the taxis dataset.

In [19]:
df_taxis = sb.load_dataset('taxis')

8. The 'pickup' column contains the date and time the customer picked up, but it's a string.  Add a column to the DataFrame, 'pickup_time', containing the value in 'pickup' as a DateTime.

In [20]:
df_taxis["pickup_time"] = pd.to_datetime(df_taxis["pickup"])

9. Create a subset of the dataframe to create a new DataFrame, taxis_one_day. This new DataFrame should have pickup_time values between '2019-03-23 00:06:00' (inclusive) and '2019-03-24 00:00:00' (exlusive).

In [21]:
mask = (df_taxis['pickup_time'] > "2019-03-23 00:06:00") & (df_taxis['pickup_time'] < "2019-03-24 00:00:00")
df_timed = df_taxis.loc[mask]
df_timed

pickup              dropoff  passengers  distance  fare  \
0     2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0   
8     2019-03-23 11:48:50  2019-03-23 12:06:14           1      3.63  15.0   
17    2019-03-23 20:50:49  2019-03-23 21:02:07           1      2.60  10.5   
117   2019-03-23 09:39:25  2019-03-23 09:56:45           0      3.60  15.5   
144   2019-03-23 18:35:01  2019-03-23 18:47:39           1      3.20  12.5   
...                   ...                  ...         ...       ...   ...   
6325  2019-03-23 20:52:40  2019-03-23 21:10:12           1      3.62  14.5   
6331  2019-03-23 11:27:00  2019-03-23 12:20:11           1      7.67  28.0   
6338  2019-03-23 18:05:38  2019-03-23 18:25:36           1      2.82  14.0   
6427  2019-03-23 18:26:09  2019-03-23 18:49:12           1      7.07  20.0   
6430  2019-03-23 22:55:18  2019-03-23 23:14:25           1      4.14  16.0   

       tip  tolls  total   color      payment                     pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card                 Lenox Hill West   
8     1.00    0.0  19.30  yellow  credit card               East Harlem South   
17    2.00    0.0  16.30  yellow  credit card                  Midtown Center   
117   3.75    0.0  22.55  yellow  credit card                  Yorkville East   
144   2.00    0.0  17.80  yellow  credit card             UN/Turtle Bay South   
...    ...    ...    ...     ...          ...                             ...   
6325  0.00    0.0  15.80   green         cash  Long Island City/Hunters Point   
6331  0.00    0.0  28.00   green         cash                 Jackson Heights   
6338  0.00    0.0  14.80   green  credit card              Claremont/Bathgate   
6427  0.00    0.0  20.00   green         cash                     Parkchester   
6430  0.00    0.0  17.30   green         cash             Crown Heights North   

                      dropoff_zone pickup_borough dropoff_borough  \
0              UN/Turtle Bay South      Manhattan       Manhattan   
8                   Midtown Center      Manhattan       Manhattan   
17               East Harlem South      Manhattan       Manhattan   
117   Penn Station/Madison Sq West      Manhattan       Manhattan   
144                   East Village      Manhattan       Manhattan   
...                            ...            ...             ...   
6325                      Steinway         Queens          Queens   
6331                       Maspeth         Queens          Queens   
6338    Spuyten Duyvil/Kingsbridge          Bronx           Bronx   
6427             East Harlem South          Bronx       Manhattan   
6430                Bushwick North       Brooklyn        Brooklyn   

             pickup_time  
0    2019-03-23 20:21:09  
8    2019-03-23 11:48:50  
17   2019-03-23 20:50:49  
117  2019-03-23 09:39:25  
144  2019-03-23 18:35:01  
...                  ...  
6325 2019-03-23 20:52:40  
6331 2019-03-23 11:27:00  
6338 2019-03-23 18:05:38  
6427 2019-03-23 18:26:09  
6430 2019-03-23 22:55:18  

[209 rows x 15 columns]

10. From the dataframe in Question 9, take the mean of the numeric columns, grouped at one hour intervals.  Save the result as df_means, and display it.

In [22]:
df_timed.groupby([df_timed["pickup_time"].dt.hour]).mean()

passengers  distance       fare       tip     tolls      total
pickup_time                                                                
0              1.000000  1.911667   8.583333  1.415000  0.000000  12.965000
1              1.250000  1.325000   7.875000  1.525000  0.000000  12.575000
2              1.727273  1.739091   8.181818  1.641818  0.000000  13.169091
3              1.500000  3.377500  11.750000  2.410000  0.000000  17.335000
4              2.000000  0.950000   5.500000  0.915000  0.000000  10.215000
5              2.000000  1.270000   6.000000  0.980000  0.000000  10.530000
6              1.000000  0.400000  21.500000  0.000000  0.000000  23.133333
7              2.333333  0.980000   5.250000  1.165000  0.000000   9.298333
8              1.000000  0.020000   2.500000  0.000000  0.000000   3.300000
9              1.500000  1.352000   7.400000  1.674000  0.000000  12.124000
10             1.000000  1.760000   8.750000  0.727500  0.000000  12.152500
11             1.909091  2.070000  11.090909  0.803636  0.000000  14.667273
12             2.000000  2.267143  10.260000  0.645714  0.000000  13.420000
13             2.500000  1.167000   7.550000  2.074000  0.000000  12.344000
14             2.470588  4.752941  18.330000  1.945294  1.003529  24.267059
15             1.000000  6.557143  22.214286  3.210000  1.645714  30.370000
16             2.000000  2.194545  10.454545  1.109091  0.000000  14.431818
17             1.090909  1.913636  14.818182  2.688182  0.523636  20.739091
18             1.571429  3.206429  12.821429  0.844286  0.411429  16.427143
19             1.526316  2.097895  10.263158  1.176316  0.000000  14.226316
20             1.400000  2.448000  11.100000  1.544000  0.000000  15.944000
21             1.000000  2.017143  10.571429  1.420000  0.000000  15.791429
22             1.307692  1.881538   8.923077  1.094615  0.000000  13.433077
23             1.615385  3.725385  15.115385  1.696154  0.000000  20.034615

Check https://colab.research.google.com/github/CodeSolid/CodeSolid.github.io/blob/main/booksource/exercises/PandasExercises.ipynb for more Pandas exercises.